### ISSUE TITLE
Hi, I'm Qian Jia, it seems that there is a problem with your school mailbox and you can't receive emails, can you send a new mailbox? Thank you

### ISSUE THREAD

**Issue by volare1996** [Maths2209/Shared-Labs-Intro-to-DS#1]
Hi, I'm Qian Jia, it seems that there is a problem with your school mailbox and you can't receive emails, can you send a new mailbox? Thank you

**Comment by dhjx1996** [comment]
Hi Qian Jia,

Hmmm, strange given we had been exchanging emails using my Columbia email, but you are welcome to send to my personal email (this email).

Best Regards,
Dion

On Dec 9, 2023, at 10:48 AM, volare1996 ***@***.***> wrote:

﻿

Hi, I'm Qian Jia, it seems that there is a problem with your school mailbox and you can't receive emails, can you send a new mailbox? Thank you

**Comment by volare1996** [comment]
Okkk, thanks!
